management:
  endpoints:
    web:
      exposure:
        include: '*'
file:
  message: Hello, Message from config client.yml file(OLD).



spring:
  application:
    name: config-client
server:
  port: 9080
